services:
  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    ports:
      - "9450:9450"
      - "8888:8888" # For testing Port Forward Wizard
    volumes:
      - slatedb-data:/tmp/nylon-wall/slatedb
    environment:
      - RUST_LOG=nylon_wall_daemon=debug
      - NYLON_WALL_IFACE=eth0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - BPF
      - NET_RAW
    sysctls:
      - net.ipv4.conf.eth0.route_localnet=1
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: nylon-wall-daemon/src
        - action: rebuild
          path: nylon-wall-common/src
        - action: rebuild
          path: nylon-wall-ebpf/src
          
volumes:
  slatedb-data:
